version: "3"
services:
  my-db:
    image: mysql
    container_name: sql-db
#    ports:
#      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
  app:
    build: .
    links:
      - my-db
    ports:
      - "8090:8080"
    depends_on:
      - my-db